export interface SampleTeam {
  name: string;
  short_code: string;
  crest_color: string;
  pot?: number;
}

export const WORLD_NATIONS: SampleTeam[] = [
  { name: "Brazil", short_code: "BRA", crest_color: "#009c3b", pot: 1 },
  { name: "Argentina", short_code: "ARG", crest_color: "#75aadb", pot: 1 },
  { name: "France", short_code: "FRA", crest_color: "#002654", pot: 1 },
  { name: "England", short_code: "ENG", crest_color: "#cf081f", pot: 1 },
  { name: "Belgium", short_code: "BEL", crest_color: "#fdda25", pot: 1 },
  { name: "Portugal", short_code: "POR", crest_color: "#006600", pot: 1 },
  { name: "Netherlands", short_code: "NED", crest_color: "#ff6b00", pot: 1 },
  { name: "Spain", short_code: "ESP", crest_color: "#c60b1e", pot: 1 },
  { name: "Germany", short_code: "GER", crest_color: "#000000", pot: 2 },
  { name: "Uruguay", short_code: "URU", crest_color: "#0038a8", pot: 2 },
  { name: "Croatia", short_code: "CRO", crest_color: "#ff0000", pot: 2 },
  { name: "Denmark", short_code: "DEN", crest_color: "#c60c30", pot: 2 },
  { name: "Mexico", short_code: "MEX", crest_color: "#006847", pot: 2 },
  { name: "USA", short_code: "USA", crest_color: "#002868", pot: 2 },
  { name: "Switzerland", short_code: "SUI", crest_color: "#d52b1e", pot: 2 },
  { name: "Senegal", short_code: "SEN", crest_color: "#00853f", pot: 2 },
  { name: "Japan", short_code: "JPN", crest_color: "#bc002d", pot: 3 },
  { name: "Morocco", short_code: "MAR", crest_color: "#c1272d", pot: 3 },
  { name: "Serbia", short_code: "SRB", crest_color: "#c6363c", pot: 3 },
  { name: "Poland", short_code: "POL", crest_color: "#dc143c", pot: 3 },
  { name: "South Korea", short_code: "KOR", crest_color: "#0047a0", pot: 3 },
  { name: "Australia", short_code: "AUS", crest_color: "#012169", pot: 3 },
  { name: "Canada", short_code: "CAN", crest_color: "#ff0000", pot: 3 },
  { name: "Ecuador", short_code: "ECU", crest_color: "#ffdd00", pot: 3 },
  { name: "Cameroon", short_code: "CMR", crest_color: "#007a5e", pot: 4 },
  { name: "Ghana", short_code: "GHA", crest_color: "#006b3f", pot: 4 },
  { name: "Costa Rica", short_code: "CRC", crest_color: "#002b7f", pot: 4 },
  { name: "Tunisia", short_code: "TUN", crest_color: "#e70013", pot: 4 },
  { name: "Iran", short_code: "IRN", crest_color: "#239f40", pot: 4 },
  { name: "Saudi Arabia", short_code: "KSA", crest_color: "#006c35", pot: 4 },
  { name: "Wales", short_code: "WAL", crest_color: "#c8102e", pot: 4 },
  { name: "Qatar", short_code: "QAT", crest_color: "#8a1538", pot: 4 },
  // Extra for WC48 / Euro
  { name: "Italy", short_code: "ITA", crest_color: "#009246", pot: 1 },
  { name: "Colombia", short_code: "COL", crest_color: "#fcd116", pot: 2 },
  { name: "Nigeria", short_code: "NGA", crest_color: "#008751", pot: 3 },
  { name: "Egypt", short_code: "EGY", crest_color: "#ce1126", pot: 3 },
  { name: "Austria", short_code: "AUT", crest_color: "#ed2939", pot: 2 },
  { name: "Turkey", short_code: "TUR", crest_color: "#e30a17", pot: 2 },
  { name: "Ukraine", short_code: "UKR", crest_color: "#0057b7", pot: 3 },
  { name: "Czechia", short_code: "CZE", crest_color: "#d7141a", pot: 3 },
  { name: "Scotland", short_code: "SCO", crest_color: "#0065bd", pot: 3 },
  { name: "Hungary", short_code: "HUN", crest_color: "#436f4d", pot: 3 },
  { name: "Algeria", short_code: "ALG", crest_color: "#006233", pot: 3 },
  { name: "Ivory Coast", short_code: "CIV", crest_color: "#f77f00", pot: 3 },
  { name: "Paraguay", short_code: "PAR", crest_color: "#0038a8", pot: 4 },
  { name: "Chile", short_code: "CHI", crest_color: "#d52b1e", pot: 4 },
  { name: "Norway", short_code: "NOR", crest_color: "#ba0c2f", pot: 2 },
  { name: "Sweden", short_code: "SWE", crest_color: "#006aa7", pot: 3 },
];

export const EURO_NATIONS: SampleTeam[] = [
  { name: "Germany", short_code: "GER", crest_color: "#000000" },
  { name: "Spain", short_code: "ESP", crest_color: "#c60b1e" },
  { name: "France", short_code: "FRA", crest_color: "#002654" },
  { name: "Portugal", short_code: "POR", crest_color: "#006600" },
  { name: "Belgium", short_code: "BEL", crest_color: "#fdda25" },
  { name: "England", short_code: "ENG", crest_color: "#cf081f" },
  { name: "Italy", short_code: "ITA", crest_color: "#009246" },
  { name: "Netherlands", short_code: "NED", crest_color: "#ff6b00" },
  { name: "Croatia", short_code: "CRO", crest_color: "#ff0000" },
  { name: "Denmark", short_code: "DEN", crest_color: "#c60c30" },
  { name: "Switzerland", short_code: "SUI", crest_color: "#d52b1e" },
  { name: "Austria", short_code: "AUT", crest_color: "#ed2939" },
  { name: "Turkey", short_code: "TUR", crest_color: "#e30a17" },
  { name: "Ukraine", short_code: "UKR", crest_color: "#0057b7" },
  { name: "Czechia", short_code: "CZE", crest_color: "#d7141a" },
  { name: "Scotland", short_code: "SCO", crest_color: "#0065bd" },
  { name: "Hungary", short_code: "HUN", crest_color: "#436f4d" },
  { name: "Poland", short_code: "POL", crest_color: "#dc143c" },
  { name: "Serbia", short_code: "SRB", crest_color: "#c6363c" },
  { name: "Romania", short_code: "ROU", crest_color: "#002b7f" },
  { name: "Slovakia", short_code: "SVK", crest_color: "#0b4ea2" },
  { name: "Slovenia", short_code: "SVN", crest_color: "#005ce6" },
  { name: "Georgia", short_code: "GEO", crest_color: "#ff0000" },
  { name: "Albania", short_code: "ALB", crest_color: "#e41e20" },
];
